---
# tasks file for webs
- name: Install the latest version of EPEL
  yum:
    name: epel-release
    state: latest

- name: Install the latest version of Nginx
  yum:
    name: nginx
    state: latest

- name: Template a file to Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
 
- name: Template a file to Nginx
  ansible.builtin.template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
  tags: html

- name: Enable a timer unit for Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes
